// Curated spam-trigger phrase list for cold B2B email deliverability checks.
//
// DATA ONLY — no logic, no imports. The matching engine lives in ./copy.ts.
//
// Sourced from the well-known published 2026 lists (Mailmeteor, Snov.io,
// Overloop, ActiveCampaign, Smartlead) and filtered to phrases that plausibly
// appear in a B2B cold email. Pharma / adult / gambling / lottery noise that
// never occurs in this product is dropped, except a small handful of classics
// filters still weight heavily.
//
// Severity guide:
//   high — clear filter-bait ("100% free", "this isn't spam", "$$$",
//          "make money fast", "risk-free", "double your")
//   med  — pushy sales language ("act now", "limited time", "buy now",
//          "order now", "click here", "special promotion")
//   low  — mild flavor, only weakly spammy ("cheap", "winner",
//          "touching base", "just following up")
//
// All phrases are lowercased. Multi-word phrases and punctuation classics
// ("$$$", "!!!") are allowed. `alternatives` (1–3 plain, non-spammy rewrites)
// are provided for the top cold-email offenders — the phrases most likely to
// actually be typed into a cold email.

export type SpamCategory =
  | "money"
  | "scam"
  | "overpromise"
  | "urgency"
  | "phishing"
  | "cold_email";

export type SpamSeverity = "high" | "med" | "low";

export interface SpamPhrase {
  phrase: string;
  category: SpamCategory;
  severity: SpamSeverity;
  alternatives?: string[];
}

export const SPAM_PHRASES: SpamPhrase[] = [
  // ── money ────────────────────────────────────────────────────────────────
  { phrase: "make money", category: "money", severity: "high", alternatives: ["grow revenue", "increase income"] },
  { phrase: "make money fast", category: "money", severity: "high" },
  { phrase: "earn money", category: "money", severity: "high", alternatives: ["grow revenue"] },
  { phrase: "earn extra cash", category: "money", severity: "high" },
  { phrase: "extra income", category: "money", severity: "high", alternatives: ["additional revenue"] },
  { phrase: "extra cash", category: "money", severity: "med" },
  { phrase: "cash bonus", category: "money", severity: "high" },
  { phrase: "cash out", category: "money", severity: "med" },
  { phrase: "fast cash", category: "money", severity: "high" },
  { phrase: "quick cash", category: "money", severity: "high" },
  { phrase: "instant cash", category: "money", severity: "high" },
  { phrase: "cold hard cash", category: "money", severity: "med" },
  { phrase: "money back", category: "money", severity: "med", alternatives: ["refundable"] },
  { phrase: "money-back guarantee", category: "money", severity: "med", alternatives: ["refund policy"] },
  { phrase: "double your income", category: "money", severity: "high" },
  { phrase: "double your", category: "money", severity: "high", alternatives: ["increase your", "grow your"] },
  { phrase: "increase sales", category: "money", severity: "low", alternatives: ["grow sales"] },
  { phrase: "increase revenue", category: "money", severity: "low", alternatives: ["grow revenue"] },
  { phrase: "big bucks", category: "money", severity: "med" },
  { phrase: "million dollars", category: "money", severity: "med" },
  { phrase: "billion", category: "money", severity: "low" },
  { phrase: "cash", category: "money", severity: "low" },
  { phrase: "$$$", category: "money", severity: "high" },
  { phrase: "money making", category: "money", severity: "high" },
  { phrase: "pure profit", category: "money", severity: "med" },
  { phrase: "profit", category: "money", severity: "low", alternatives: ["margin", "return"] },
  { phrase: "financial freedom", category: "money", severity: "med" },
  { phrase: "save big money", category: "money", severity: "high" },
  { phrase: "save up to", category: "money", severity: "low", alternatives: ["reduce by up to"] },
  { phrase: "hidden charges", category: "money", severity: "med" },
  { phrase: "no hidden costs", category: "money", severity: "med", alternatives: ["transparent pricing"] },
  { phrase: "no hidden fees", category: "money", severity: "med", alternatives: ["transparent pricing"] },
  { phrase: "investment", category: "money", severity: "low" },
  { phrase: "earnings", category: "money", severity: "low" },

  // ── scam ─────────────────────────────────────────────────────────────────
  { phrase: "this isn't spam", category: "scam", severity: "high" },
  { phrase: "this is not spam", category: "scam", severity: "high" },
  { phrase: "not spam", category: "scam", severity: "high" },
  { phrase: "you have been selected", category: "scam", severity: "high" },
  { phrase: "you've been selected", category: "scam", severity: "high" },
  { phrase: "you are a winner", category: "scam", severity: "high" },
  { phrase: "you're a winner", category: "scam", severity: "high" },
  { phrase: "winner", category: "scam", severity: "low", alternatives: ["selected", "shortlisted"] },
  { phrase: "congratulations", category: "scam", severity: "low", alternatives: ["nice work", "well done"] },
  { phrase: "you won", category: "scam", severity: "high" },
  { phrase: "claim your prize", category: "scam", severity: "high" },
  { phrase: "claim now", category: "scam", severity: "high" },
  { phrase: "free prize", category: "scam", severity: "high" },
  { phrase: "no catch", category: "scam", severity: "med", alternatives: ["no strings attached"] },
  { phrase: "no strings attached", category: "scam", severity: "med" },
  { phrase: "no gimmick", category: "scam", severity: "med" },
  { phrase: "no gimmicks", category: "scam", severity: "med" },
  { phrase: "this is not a scam", category: "scam", severity: "high" },
  { phrase: "legitimate", category: "scam", severity: "low" },
  { phrase: "100% satisfied", category: "scam", severity: "med" },
  { phrase: "consolidate your debt", category: "scam", severity: "high" },
  { phrase: "eliminate debt", category: "scam", severity: "high" },
  { phrase: "be your own boss", category: "scam", severity: "med" },
  { phrase: "work from home", category: "scam", severity: "low" },
  { phrase: "no experience needed", category: "scam", severity: "med" },
  { phrase: "as seen on", category: "scam", severity: "med" },
  { phrase: "acceptance", category: "scam", severity: "low" },
  { phrase: "meet singles", category: "scam", severity: "high" },
  { phrase: "multi-level marketing", category: "scam", severity: "med" },

  // ── overpromise ───────────────────────────────────────────────────────────
  { phrase: "100% free", category: "overpromise", severity: "high", alternatives: ["at no cost", "complimentary"] },
  { phrase: "100% guaranteed", category: "overpromise", severity: "high", alternatives: ["backed by our commitment"] },
  { phrase: "100% satisfaction", category: "overpromise", severity: "med" },
  { phrase: "risk-free", category: "overpromise", severity: "high", alternatives: ["no commitment", "low risk"] },
  { phrase: "risk free", category: "overpromise", severity: "high", alternatives: ["no commitment", "low risk"] },
  { phrase: "guarantee", category: "overpromise", severity: "med", alternatives: ["ensure", "commit to"] },
  { phrase: "guaranteed", category: "overpromise", severity: "med", alternatives: ["reliably", "dependably"] },
  { phrase: "satisfaction guaranteed", category: "overpromise", severity: "med" },
  { phrase: "no obligation", category: "overpromise", severity: "med", alternatives: ["no commitment"] },
  { phrase: "no cost", category: "overpromise", severity: "med", alternatives: ["complimentary", "on us"] },
  { phrase: "no fees", category: "overpromise", severity: "med", alternatives: ["included"] },
  { phrase: "no purchase necessary", category: "overpromise", severity: "med" },
  { phrase: "no questions asked", category: "overpromise", severity: "med" },
  { phrase: "no credit check", category: "overpromise", severity: "high" },
  { phrase: "free", category: "overpromise", severity: "med", alternatives: ["complimentary", "at no charge", "on us"] },
  { phrase: "free trial", category: "overpromise", severity: "low", alternatives: ["trial", "test drive"] },
  { phrase: "free gift", category: "overpromise", severity: "med", alternatives: ["complimentary gift"] },
  { phrase: "free access", category: "overpromise", severity: "med", alternatives: ["complimentary access"] },
  { phrase: "free consultation", category: "overpromise", severity: "low", alternatives: ["complimentary consultation", "intro call"] },
  { phrase: "free quote", category: "overpromise", severity: "low", alternatives: ["quote", "estimate"] },
  { phrase: "free sample", category: "overpromise", severity: "low", alternatives: ["sample"] },
  { phrase: "free offer", category: "overpromise", severity: "med" },
  { phrase: "free money", category: "overpromise", severity: "high" },
  { phrase: "free info", category: "overpromise", severity: "med" },
  { phrase: "free preview", category: "overpromise", severity: "low" },
  { phrase: "for free", category: "overpromise", severity: "med", alternatives: ["at no charge"] },
  { phrase: "best price", category: "overpromise", severity: "med", alternatives: ["competitive pricing"] },
  { phrase: "lowest price", category: "overpromise", severity: "med", alternatives: ["competitive pricing"] },
  { phrase: "lowest rate", category: "overpromise", severity: "med", alternatives: ["competitive rate"] },
  { phrase: "unbeatable", category: "overpromise", severity: "med", alternatives: ["strong value"] },
  { phrase: "unbeatable offer", category: "overpromise", severity: "med" },
  { phrase: "unbeatable price", category: "overpromise", severity: "med" },
  { phrase: "why pay more", category: "overpromise", severity: "med" },
  { phrase: "bargain", category: "overpromise", severity: "low" },
  { phrase: "best deal", category: "overpromise", severity: "med", alternatives: ["strong offer"] },
  { phrase: "amazing", category: "overpromise", severity: "low", alternatives: ["strong", "notable"] },
  { phrase: "amazing offer", category: "overpromise", severity: "med" },
  { phrase: "incredible deal", category: "overpromise", severity: "med" },
  { phrase: "once in a lifetime", category: "overpromise", severity: "med" },
  { phrase: "the best", category: "overpromise", severity: "low" },
  { phrase: "number one", category: "overpromise", severity: "low", alternatives: ["a leading"] },
  { phrase: "#1", category: "overpromise", severity: "low", alternatives: ["a leading"] },
  { phrase: "world class", category: "overpromise", severity: "low" },
  { phrase: "revolutionary", category: "overpromise", severity: "low", alternatives: ["new", "modern"] },
  { phrase: "guaranteed results", category: "overpromise", severity: "high", alternatives: ["proven results"] },
  { phrase: "instant results", category: "overpromise", severity: "med", alternatives: ["fast results"] },
  { phrase: "problem solved", category: "overpromise", severity: "low" },
  { phrase: "promise you", category: "overpromise", severity: "low" },
  { phrase: "cheap", category: "overpromise", severity: "low", alternatives: ["affordable", "cost-effective"] },
  { phrase: "cheapest", category: "overpromise", severity: "med", alternatives: ["most affordable"] },
  { phrase: "clearance", category: "overpromise", severity: "low" },
  { phrase: "discount", category: "overpromise", severity: "low", alternatives: ["reduced rate"] },
  { phrase: "huge discount", category: "overpromise", severity: "med" },
  { phrase: "big savings", category: "overpromise", severity: "med", alternatives: ["meaningful savings"] },
  { phrase: "save money", category: "overpromise", severity: "low", alternatives: ["reduce costs"] },

  // ── urgency ──────────────────────────────────────────────────────────────
  { phrase: "act now", category: "urgency", severity: "med", alternatives: ["let me know if useful", "happy to share more"] },
  { phrase: "act immediately", category: "urgency", severity: "med" },
  { phrase: "act fast", category: "urgency", severity: "med" },
  { phrase: "apply now", category: "urgency", severity: "med", alternatives: ["apply when ready"] },
  { phrase: "buy now", category: "urgency", severity: "med", alternatives: ["learn more", "take a look"] },
  { phrase: "buy today", category: "urgency", severity: "med" },
  { phrase: "buy direct", category: "urgency", severity: "med" },
  { phrase: "order now", category: "urgency", severity: "med", alternatives: ["place an order when ready"] },
  { phrase: "order today", category: "urgency", severity: "med" },
  { phrase: "call now", category: "urgency", severity: "med", alternatives: ["reach out anytime"] },
  { phrase: "click here", category: "urgency", severity: "med", alternatives: ["see here", "take a look"] },
  { phrase: "click below", category: "urgency", severity: "med", alternatives: ["see below"] },
  { phrase: "click to", category: "urgency", severity: "low" },
  { phrase: "sign up now", category: "urgency", severity: "med", alternatives: ["sign up when ready"] },
  { phrase: "subscribe now", category: "urgency", severity: "med" },
  { phrase: "get started now", category: "urgency", severity: "low", alternatives: ["get started whenever"] },
  { phrase: "don't wait", category: "urgency", severity: "med", alternatives: ["whenever it suits you"] },
  { phrase: "don't delay", category: "urgency", severity: "med" },
  { phrase: "don't hesitate", category: "urgency", severity: "low" },
  { phrase: "hurry", category: "urgency", severity: "med", alternatives: ["no rush"] },
  { phrase: "hurry up", category: "urgency", severity: "med" },
  { phrase: "limited time", category: "urgency", severity: "med", alternatives: ["ongoing", "open-ended"] },
  { phrase: "limited time offer", category: "urgency", severity: "med", alternatives: ["current offer"] },
  { phrase: "limited offer", category: "urgency", severity: "med" },
  { phrase: "limited spots", category: "urgency", severity: "med", alternatives: ["a few openings"] },
  { phrase: "limited availability", category: "urgency", severity: "med" },
  { phrase: "while supplies last", category: "urgency", severity: "med" },
  { phrase: "expires", category: "urgency", severity: "low" },
  { phrase: "expires today", category: "urgency", severity: "med" },
  { phrase: "offer expires", category: "urgency", severity: "med" },
  { phrase: "ends soon", category: "urgency", severity: "med" },
  { phrase: "ends today", category: "urgency", severity: "med" },
  { phrase: "last chance", category: "urgency", severity: "med", alternatives: ["one more nudge"] },
  { phrase: "final notice", category: "urgency", severity: "med" },
  { phrase: "final reminder", category: "urgency", severity: "low" },
  { phrase: "urgent", category: "urgency", severity: "med", alternatives: ["quick note", "timely"] },
  { phrase: "immediate action", category: "urgency", severity: "med" },
  { phrase: "instant", category: "urgency", severity: "low" },
  { phrase: "instant access", category: "urgency", severity: "low", alternatives: ["immediate access"] },
  { phrase: "now only", category: "urgency", severity: "med" },
  { phrase: "today only", category: "urgency", severity: "med" },
  { phrase: "one time only", category: "urgency", severity: "med" },
  { phrase: "special promotion", category: "urgency", severity: "med", alternatives: ["current offer"] },
  { phrase: "special offer", category: "urgency", severity: "med", alternatives: ["a note", "something worth a look"] },
  { phrase: "special deal", category: "urgency", severity: "med" },
  { phrase: "exclusive offer", category: "urgency", severity: "med", alternatives: ["an offer for you"] },
  { phrase: "exclusive deal", category: "urgency", severity: "med" },
  // NOTE: runs of "!"/"?" are intentionally NOT listed here — the structural
  // [!?]{2,} check in copy.ts already scores repeated punctuation. Listing "!!"
  // as a phrase too would double-count the same signal.

  // ── phishing ─────────────────────────────────────────────────────────────
  { phrase: "click here to confirm", category: "phishing", severity: "high" },
  { phrase: "verify your account", category: "phishing", severity: "high" },
  { phrase: "verify your information", category: "phishing", severity: "high" },
  { phrase: "confirm your identity", category: "phishing", severity: "high" },
  { phrase: "confirm your account", category: "phishing", severity: "high" },
  { phrase: "update your account", category: "phishing", severity: "high" },
  { phrase: "update your payment", category: "phishing", severity: "high" },
  { phrase: "your account has been", category: "phishing", severity: "med" },
  { phrase: "account suspended", category: "phishing", severity: "high" },
  { phrase: "account will be closed", category: "phishing", severity: "high" },
  { phrase: "unauthorized access", category: "phishing", severity: "med" },
  { phrase: "suspicious activity", category: "phishing", severity: "med" },
  { phrase: "login to verify", category: "phishing", severity: "high" },
  { phrase: "reset your password", category: "phishing", severity: "med" },
  { phrase: "credit card", category: "phishing", severity: "med", alternatives: ["payment details"] },
  { phrase: "credit card offers", category: "phishing", severity: "high" },
  { phrase: "credit card number", category: "phishing", severity: "high" },
  { phrase: "social security number", category: "phishing", severity: "high" },
  { phrase: "bank account", category: "phishing", severity: "med" },
  { phrase: "wire transfer", category: "phishing", severity: "med" },
  { phrase: "billing information", category: "phishing", severity: "med" },
  { phrase: "click the link below", category: "phishing", severity: "med", alternatives: ["see the link below"] },
  { phrase: "click this link", category: "phishing", severity: "med", alternatives: ["here's a link"] },
  { phrase: "download now", category: "phishing", severity: "med", alternatives: ["download when ready"] },
  { phrase: "open attachment", category: "phishing", severity: "med" },
  { phrase: "dear friend", category: "phishing", severity: "high", alternatives: ["hi there"] },
  { phrase: "dear customer", category: "phishing", severity: "med", alternatives: ["hi there"] },
  { phrase: "dear sir", category: "phishing", severity: "med", alternatives: ["hi there"] },
  { phrase: "dear sir/madam", category: "phishing", severity: "med", alternatives: ["hi there"] },
  { phrase: "valued customer", category: "phishing", severity: "med", alternatives: ["hi there"] },

  // ── cold_email ───────────────────────────────────────────────────────────
  { phrase: "touching base", category: "cold_email", severity: "low", alternatives: ["following up", "checking in"] },
  { phrase: "just following up", category: "cold_email", severity: "low", alternatives: ["following up on my note"] },
  { phrase: "just checking in", category: "cold_email", severity: "low", alternatives: ["a quick follow-up"] },
  { phrase: "circling back", category: "cold_email", severity: "low", alternatives: ["following up"] },
  { phrase: "reaching out", category: "cold_email", severity: "low", alternatives: ["getting in touch"] },
  { phrase: "quick question", category: "cold_email", severity: "low", alternatives: ["a question for you"] },
  { phrase: "picking your brain", category: "cold_email", severity: "low", alternatives: ["getting your take"] },
  { phrase: "hope this email finds you well", category: "cold_email", severity: "low", alternatives: ["hope your week's going well"] },
  { phrase: "hope this finds you well", category: "cold_email", severity: "low", alternatives: ["hope your week's going well"] },
  { phrase: "i wanted to reach out", category: "cold_email", severity: "low", alternatives: ["i'm getting in touch"] },
  { phrase: "per my last email", category: "cold_email", severity: "low", alternatives: ["following up on my note"] },
  { phrase: "as per my previous email", category: "cold_email", severity: "low", alternatives: ["following up on my note"] },
  { phrase: "did you get a chance", category: "cold_email", severity: "low", alternatives: ["curious if you saw this"] },
  { phrase: "bumping this to the top", category: "cold_email", severity: "low" },
  { phrase: "let me know your thoughts", category: "cold_email", severity: "low", alternatives: ["curious what you think"] },
  { phrase: "does that work for you", category: "cold_email", severity: "low" },
  { phrase: "worth a quick chat", category: "cold_email", severity: "low", alternatives: ["worth a short call"] },
  { phrase: "grab 15 minutes", category: "cold_email", severity: "low", alternatives: ["a short call"] },
  { phrase: "jump on a call", category: "cold_email", severity: "low", alternatives: ["a quick call"] },
  { phrase: "hop on a call", category: "cold_email", severity: "low", alternatives: ["a quick call"] },
  { phrase: "book a demo", category: "cold_email", severity: "low", alternatives: ["see it in action"] },
  { phrase: "schedule a demo", category: "cold_email", severity: "low", alternatives: ["see it in action"] },
  { phrase: "game changer", category: "cold_email", severity: "low", alternatives: ["a real difference"] },
  { phrase: "game-changer", category: "cold_email", severity: "low", alternatives: ["a real difference"] },
  { phrase: "synergy", category: "cold_email", severity: "low", alternatives: ["a good fit"] },
  { phrase: "move the needle", category: "cold_email", severity: "low", alternatives: ["make a difference"] },
  { phrase: "low hanging fruit", category: "cold_email", severity: "low", alternatives: ["quick wins"] },
  { phrase: "low-hanging fruit", category: "cold_email", severity: "low", alternatives: ["quick wins"] },
  { phrase: "no brainer", category: "cold_email", severity: "low", alternatives: ["an easy call"] },
  { phrase: "no-brainer", category: "cold_email", severity: "low", alternatives: ["an easy call"] },
  { phrase: "cutting edge", category: "cold_email", severity: "low", alternatives: ["modern"] },
  { phrase: "cutting-edge", category: "cold_email", severity: "low", alternatives: ["modern"] },
  { phrase: "state of the art", category: "cold_email", severity: "low", alternatives: ["modern"] },
  { phrase: "best in class", category: "cold_email", severity: "low", alternatives: ["a leading option"] },
  { phrase: "best-in-class", category: "cold_email", severity: "low", alternatives: ["a leading option"] },
  { phrase: "unsubscribe", category: "cold_email", severity: "low" },
  { phrase: "opt out", category: "cold_email", severity: "low" },
  { phrase: "opt-in", category: "cold_email", severity: "low" },
  { phrase: "remove me", category: "cold_email", severity: "low" },
  { phrase: "this email was sent to", category: "cold_email", severity: "low" },
  { phrase: "not interested", category: "cold_email", severity: "low" },
];
