// POST /api/admin/domains/[id]/dkim: write the DKIM TXT record. DKIM keys are
// generated by hand in the Google Admin console (Google exposes no API for it);
// the owner pastes the record value here and we write it at the registrar (or,
// for a manual registrar, hand it back for copy-paste). The provisioning DKIM
// step's live probe then detects it and flips the domain to warming.
// Owner only, org-scoped.

import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireOwner } from "@/lib/auth/require-owner";
import { loadRegistrarConfig, providerFor } from "@/lib/registrar/auth";
import type { DnsRecordInput } from "@/lib/registrar/types";
import type { SendingDomain } from "@/types/app";

interface RouteParams {
  params: Promise<{ id: string }>;
}

interface DkimBody {
  value?: string; // the TXT record value (e.g. "v=DKIM1; k=rsa; p=…")
  selector?: string; // default "google" (Workspace's default selector)
}

export const maxDuration = 60;

export async function POST(req: NextRequest, { params }: RouteParams) {
  const auth = await requireOwner();
  if (auth.error) return auth.error;
  const { organizationId } = auth;
  const { id } = await params;

  const body = (await req.json().catch(() => null)) as DkimBody | null;
  const value = (body?.value ?? "").trim();
  const selector = (body?.selector ?? "google").trim().toLowerCase();
  if (!/^v=dkim1/i.test(value) && !/p=/.test(value)) {
    return NextResponse.json(
      { error: "That doesn't look like a DKIM record. Paste the value from Google Admin (starts with v=DKIM1)." },
      { status: 400 },
    );
  }
  if (!/^[a-z0-9_-]+$/.test(selector)) {
    return NextResponse.json({ error: "Invalid DKIM selector." }, { status: 400 });
  }

  const admin = createAdminClient();
  const { data: domain } = await admin
    .from("sending_domains")
    .select("*")
    .eq("id", id)
    .eq("organization_id", organizationId)
    .maybeSingle();
  if (!domain) {
    return NextResponse.json({ error: "Domain not found" }, { status: 404 });
  }
  const d = domain as SendingDomain;

  const record: DnsRecordInput = {
    type: "TXT",
    name: `${selector}._domainkey`,
    content: value,
  };

  if (d.registrar === "manual") {
    return NextResponse.json({ applied: false, manual: true, record });
  }

  const config = await loadRegistrarConfig(admin, organizationId);
  const provider = providerFor(config, d.registrar);
  if (!provider) {
    return NextResponse.json(
      { error: `The ${d.registrar} registrar isn't configured. Add its API key in Settings.`, record },
      { status: 400 },
    );
  }
  try {
    await provider.upsertDnsRecords(d.domain, [record]);
  } catch (err) {
    return NextResponse.json(
      { error: `Writing the DKIM record failed at ${d.registrar}: ${err instanceof Error ? err.message : String(err)}`, record },
      { status: 502 },
    );
  }
  return NextResponse.json({ applied: true, record });
}
